import { Car } from './car';

export const CARS: Car[] = [
  { id: 1,  model: 'Proton Perdana', image: '../assets/img/proton-perdana.jpg', year: '2018', description: 'The Proton Perdana is a series of four-door mid-size saloon cars produced by Malaysian automobile manufacturer Proton.'},
  { id: 2,  model: 'Proton Exora', image: '../assets/img/proton-exora.jpg', year: '2018', description: 'The Proton Exora is a compact MPV produced by Malaysian car manufacturer Proton. It became Malaysia\'s first home-grown MPV upon its release on 15 April 2009. The Exora is the first Proton to be based on the new P2 platform, and its facelift revision which debuted on 15 December 2011 became the first Proton to use the new CamPro CFE turbocharged engine and CVT technology.'},
  { id: 3,  model: 'Proton Iriz', image: '../assets/img/proton-iriz.png', year: '2018', description:'Meet the Iriz: a small car that’s big on comfort, bigger on safety. With its 5-Star ASEAN NCAP safety rating, it’s the hottest hatchback on the block that’s both fun and safe. Find out more about the Iriz and test drive one today.'},
  { id: 4,  model: 'Perodua Myvi', image: '../assets/img/perodua-myvi.jpg', year: '2019', description:'The Perodua Myvi is a subcompact car/supermini (B-segment) produced by the Malaysian manufacturer Perodua since 2005. The Myvi is the result of Perodua\'s collaboration with both Toyota and Daihatsu. The Myvi was the best-selling car in Malaysia for 8 consecutive years, between 2006 and 2013.As of February 2019, the Myvi reached nearly 1.1 million units sold since the launched of its first generation in 2005.'},
  { id: 5,  model: 'Perodua Axia', image: '../assets/img/perodua-axia.jpg', year: '2018', description:'The Perodua Axia is a five-door hatchback produced by Malaysian automobile manufacturer Perodua. It was launched on 15 September 2014 as the successor to the Viva. The car takes over the title of being the most affordable car in Malaysia from the Viva'},
  { id: 6,  model: 'Perodua Alza', image: '../assets/img/perodua-alza.jpg', year: '2019', description:'The Perodua Alza is a B-segment MPV produced by Malaysian automobile manufacturer Perodua. It was launched on 23 November 2009 as the company\'s first purpose-built MPV.The Perodua Alza is based on the Daihatsu Boon Luminas platform and powered by the 1.5-litre 3SZ-VE DVVT engine.'},
  { id: 7,  model: 'Perodua Bezza', image: '../assets/img/perodua-bezza.jpg', year: '2018', description:'The Perodua Bezza (codenamed D63D) is an A-segment sedan produced by Malaysian automobile manufacturer Perodua. It was launched on 21 July 2016 as Perodua\'s first sedan car, and a complement to the Axia hatchback.'},
  { id: 8,  model: 'Toyota Vios', image: '../assets/img/toyota-vios.jpg', year: '2019', description:'The Toyota Vios is a subcompact car produced by the Japanese manufacturer Toyota, primarily for markets in the Asia-Pacific region since 2002. The second generation Vios is known as the Belta in Japan and Yaris sedan in the United States, Canada, Trinidad and Tobago, Jamaica, the Middle East and Australia.'},
  { id: 9,  model: 'Toyota Avanza', image: '../assets/img/toyota-avanza.jpg', year: '2018', description:'The Toyota Avanza is a mini MPV designed and produced by Daihatsu and marketed by Toyota. It is produced in Indonesia[3] and also contract assembled in Malaysia (under Perodua) for the first generation model. Daihatsu designed and manufactures the vehicle, which is then sold by both Daihatsu and Toyota under Daihatsu Xenia and Avanza nameplate respectively under a consigned production and OEM manufacturing agreement.'},
  { id: 10,  model: 'Honda Civic', image: '../assets/img/honda-civic.jpg', year: '2019', description:'The Honda Civic (Japanese: ホンダ・シビック, Honda Shibikku) is a line of cars manufactured by Honda. Originally a subcompact, the Civic has gone through several generational changes, becoming both larger and more upscale, moving into the compact car segment. EPA guidelines for vehicle size class stipulate a car having combined passenger and cargo room of 110 to 119.9 cubic feet (3,110 to 3,400 L) is considered a mid-size car, and as such the tenth generation Civic sedan is technically a small-end mid-size car, although it still competes in the compact class.'},
];
